In [1]:
import numpy as np
from MountainCarEnv import MountainCarEnv

In [2]:
env = MountainCarEnv(render_mode="human")

In [3]:
def epsilon_greedy_policy(state, Q, epsilon=0.1):
    explore = np.random.binomial(1, epsilon)
    if explore:
        action = env.action_space.sample()
        print('explore')
    # exploit
    else:
        action = np.argmax(Q[state])
        print('exploit')
    return action

In [4]:
def optimal_policy(state, Q):
    action = np.argmax(Q[state])
    return action

In [5]:
pos_space = np.linspace(-1.1, 0.5, 10)
vel_space = np.linspace(-0.07, 0.07, 6)
pos_space


array([-1.1       , -0.92222222, -0.74444444, -0.56666667, -0.38888889,
       -0.21111111, -0.03333333,  0.14444444,  0.32222222,  0.5       ])

In [6]:
vel_space

array([-0.07 , -0.042, -0.014,  0.014,  0.042,  0.07 ])

In [7]:
def get_state(obs):
    pos, vel = obs
    pos_bin = np.digitize(pos, pos_space)
    vel_bin = np.digitize(vel, vel_space)
    return pos_bin, vel_bin

In [8]:
pos_bin, vel_bin = get_state((-1.1, -0.07))

In [9]:
pos_bin

1

In [10]:
vel_bin

1

In [11]:
state = get_state(np.array([-0.4, 0.2]))
state

(4, 6)

In [8]:
actions = list(range(env.action_space.n))
actions

[0, 1, 2]

In [ ]:
Q = np.zeros((11,3,3))
Q

In [ ]:
obs = env.reset()
print(obs)
done = False
while not done:
    state = get_state(obs)
    action = epsilon_greedy_policy(state, Q, 0.5)
    obs, reward, done, _ = env.step(action)
    print('->', state, action, reward, obs, done)
    env.render()

# cosas de internet

In [13]:
num_states = (env.observation_space.high - env.observation_space.low)*\
                    np.array([10, 100])
num_states = np.round(num_states, 0).astype(int) + 1
num_states

array([19, 15])

In [1]:
lista = [20] * 2
lista

[20, 20]

In [4]:
DISCRETE_OS_SIZE = [20] * len(env.observation_space.high)
DISCRETE_OS_SIZE


[20, 20]

In [5]:
discrete_os_win_size = (env.observation_space.high - env.observation_space.low) / DISCRETE_OS_SIZE
discrete_os_win_size

array([0.09 , 0.007])

In [7]:
(env.observation_space.high - env.observation_space.low)

array([1.8000001, 0.14     ], dtype=float32)

In [13]:
a = np.array([100, 100]) 
a / DISCRETE_OS_SIZE

array([5., 5.])

In [6]:
q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))
q_table

array([[[-1.71966894, -1.22550192, -1.09837043],
        [-0.38862546, -0.67841013, -0.89347137],
        [-1.31999544, -0.1434014 , -1.39818642],
        ...,
        [-0.81804172, -0.63139274, -1.50627044],
        [-1.2144762 , -0.19724916, -0.45545538],
        [-1.2594207 , -0.04046355, -0.72119487]],

       [[-1.65912775, -0.28561593, -0.48903066],
        [-1.71024978, -1.89487581, -0.58478644],
        [-0.5068032 , -1.31770965, -1.72804993],
        ...,
        [-1.48958278, -0.37242411, -1.15166729],
        [-1.39798567, -0.12656022, -1.82107256],
        [-1.85984532, -0.04009123, -1.9943087 ]],

       [[-1.80873833, -0.02153282, -1.39830197],
        [-0.54824191, -1.55881193, -0.29768752],
        [-1.47512209, -0.90200176, -0.34170931],
        ...,
        [-1.49601083, -1.05829712, -1.51889538],
        [-1.27050759, -0.10458277, -1.37407762],
        [-0.35570218, -1.75938111, -0.56519119]],

       ...,

       [[-1.17500431, -0.94694098, -1.63746406],
        [-0